apiVersion: v1
kind: Service
metadata: 
  name: simple-app-service
spec:
  selector:
    name: simple-app
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 7000
      targetPort: 3000
      nodePort: 30002